# Generated by Django 4.1.7 on 2023-03-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phrase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_en", models.CharField(max_length=20)),
                ("base_ja", models.CharField(max_length=20)),
                ("prsnt_con_en", models.CharField(max_length=20)),
                ("prsnt_con_ja", models.CharField(max_length=20)),
                ("past_smpl_en", models.CharField(max_length=20)),
                ("past_smpl_ja", models.CharField(max_length=20)),
                ("past_prtcpl_en", models.CharField(max_length=20)),
                ("past_prtcpl_ja", models.CharField(max_length=20)),
                ("tps_en", models.CharField(max_length=20)),
                ("tps_ja", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "personal_pronoun",
                    models.CharField(
                        choices=[
                            ("FPS", "一人称単数"),
                            ("FPP", "一人称複数"),
                            ("SPS", "二人称単数"),
                            ("SPP", "二人称単数"),
                            ("TPS", "三人称単数"),
                            ("TPP", "三人称単数"),
                        ],
                        max_length=3,
                    ),
                ),
                ("text", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("positive_prsnt_smpl", models.CharField(max_length=50)),
                ("positive_prsnt_con", models.CharField(max_length=50)),
                ("positive_past_smpl", models.CharField(max_length=50)),
                ("positive_futr_smpl", models.CharField(max_length=50)),
                ("negative_prsnt_smpl", models.CharField(max_length=50)),
                ("negative_prsnt_con", models.CharField(max_length=50)),
                ("negative_past_smpl", models.CharField(max_length=50)),
                ("negative_futr_smpl", models.CharField(max_length=50)),
                ("question_prsnt_smpl", models.CharField(max_length=50)),
                ("question_prsnt_con", models.CharField(max_length=50)),
                ("question_past_smpl", models.CharField(max_length=50)),
                ("question_futr_smpl", models.CharField(max_length=50)),
            ],
        ),
    ]
