# Generated by Django 4.1.7 on 2023-03-19 00:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Phrase",
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
        migrations.DeleteModel(
            name="Template",
        ),
    ]
