# Generated by Django 4.1.7 on 2023-03-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("gym", "0002_delete_phrase_delete_subject_delete_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "personal_pronoun",
                    models.CharField(
                        choices=[
                            ("FPS", "一人称単数"),
                            ("FPP", "一人称複数"),
                            ("SPS", "二人称単数"),
                            ("SPP", "二人称複数"),
                            ("TPS", "三人称単数"),
                            ("TPP", "三人称複数"),
                        ],
                        max_length=3,
                    ),
                ),
                ("text", models.CharField(max_length=4)),
            ],
        ),
    ]
