# Generated by Django 4.1.7 on 2023-03-19 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sentence_type",
                    models.CharField(
                        choices=[("POS", "肯定文"), ("NEG", "否定文"), ("QUE", "疑問文")],
                        max_length=3,
                    ),
                ),
                (
                    "tense",
                    models.CharField(
                        choices=[
                            ("PRT_SMP", "現在"),
                            ("PRT_CON", "現在進行"),
                            ("PST_SMP", "過去"),
                            ("FTR_SMP", "未来"),
                        ],
                        max_length=7,
                    ),
                ),
                ("text", models.CharField(max_length=30)),
            ],
        ),
    ]
