# Generated by Django 4.1.7 on 2023-03-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0004_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="text",
            field=models.CharField(max_length=40),
        ),
    ]
