# Generated by Django 4.1.7 on 2023-03-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0005_alter_template_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="text",
            field=models.CharField(max_length=50),
        ),
    ]
