# Generated by Django 4.1.7 on 2023-03-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0006_alter_template_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Phrase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verb_form",
                    models.CharField(
                        choices=[
                            ("BASE", "基本形"),
                            ("PASM", "過去形"),
                            ("PAPA", "過去分詞"),
                            ("PRPA", "現在分詞"),
                            ("THPS", "三人称単数"),
                        ],
                        max_length=4,
                    ),
                ),
                ("japanese", models.CharField(max_length=20)),
                ("english", models.CharField(max_length=20)),
            ],
        ),
    ]
