# Generated by Django 4.1.7 on 2023-03-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0007_phrase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phrase",
            name="japanese",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
