# Generated by Django 4.1.7 on 2023-03-19 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0008_alter_phrase_japanese"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhraseGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="gym.phrase"
                    ),
                ),
            ],
        ),
    ]
