# Generated by Django 4.1.7 on 2023-03-19 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0009_phrasegroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="phrasegroup",
            name="past_simple",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="past_simple",
                to="gym.phrase",
            ),
        ),
        migrations.AlterField(
            model_name="phrasegroup",
            name="base",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="base",
                to="gym.phrase",
            ),
        ),
    ]
