# Generated by Django 4.1.7 on 2023-03-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0017_remove_phrase_verb_form_phrasebase_verb_form_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="phrasegroup",
            name="name",
            field=models.CharField(
                choices=[
                    ("PRT_SMP", "現在"),
                    ("PRT_CON", "現在進行"),
                    ("PST_SMP", "過去"),
                    ("FTR_SMP", "未来"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
