# Generated by Django 4.1.7 on 2023-03-26 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0020_alter_phrasegroup_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phrasebase",
            name="phrase_group",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="base",
                to="gym.phrasegroup",
            ),
        ),
        migrations.AlterField(
            model_name="phrasepastparticiple",
            name="phrase_group",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="past_participle",
                to="gym.phrasegroup",
            ),
        ),
        migrations.AlterField(
            model_name="phrasepastsimple",
            name="phrase_group",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="past_simple",
                to="gym.phrasegroup",
            ),
        ),
        migrations.AlterField(
            model_name="phrasepresentparticiple",
            name="phrase_group",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="present_participle",
                to="gym.phrasegroup",
            ),
        ),
        migrations.AlterField(
            model_name="phrasethirdpersonsingular",
            name="phrase_group",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="third_person_singular",
                to="gym.phrasegroup",
            ),
        ),
    ]
