# Generated by Django 4.1.7 on 2023-04-04 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0021_alter_phrasebase_phrase_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beverb",
            name="tense",
            field=models.CharField(
                choices=[
                    ("PRT_SMP", "普段"),
                    ("PRT_CON", "今"),
                    ("PST_SMP", "過去"),
                    ("FTR_SMP", "未来"),
                ],
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="paverb",
            name="tense",
            field=models.CharField(
                choices=[
                    ("PRT_SMP", "普段"),
                    ("PRT_CON", "今"),
                    ("PST_SMP", "過去"),
                    ("FTR_SMP", "未来"),
                ],
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="sentence_type",
            field=models.CharField(
                choices=[("POS", "肯定"), ("NEG", "否定"), ("QUE", "疑問")], max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="tense",
            field=models.CharField(
                choices=[
                    ("PRT_SMP", "普段"),
                    ("PRT_CON", "今"),
                    ("PST_SMP", "過去"),
                    ("FTR_SMP", "未来"),
                ],
                max_length=7,
            ),
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[("SCD", "成功"), ("FLD", "失敗")], max_length=3
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "phrase_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gym.phrasegroup",
                    ),
                ),
            ],
        ),
    ]
