# Generated by Django 4.1.7 on 2023-04-04 09:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0022_alter_beverb_tense_alter_paverb_tense_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="History",
            new_name="Log",
        ),
    ]
