# Generated by Django 4.1.7 on 2023-04-04 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0024_alter_log_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="phrase_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="gym.phrasegroup",
            ),
        ),
    ]
