# Generated by Django 4.1.7 on 2023-04-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym", "0025_alter_log_phrase_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="phrasegroup",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
